config/routes.rb
Rails.application.routes.draw do

  # specific / named routes at top

  get 'sign_in', to: 'sessions#new', as: 'sign_in'
  post 'sign_in', to: 'sessions#create'
  get 'sign_out', to: 'sessions#destroy'
  get 'landing', to: 'pages#landing', as: 'landing'

  # resources in the middle

  resources :courses, only: [:index, :new, :create, :show, :edit, :update] do
    resources :offer_dates
  end

  resources :enrollments, only: [:index, :new, :create, :show]
  resources :students, only: [:index, :new, :create, :show, :edit, :update] do
    collection { post :import }
  end
  resources :users, only: [:index, :new, :create, :show, :edit, :update]

  # Translations example. Not in use. Probably won't work on Heroku.
  # resources :translations, only: [:index, :create]

  # nonspecific / catch-all routes at the bottom

  root to: 'home#index'
end

app/models/student.rb
class Student < ActiveRecord::Base
  has_many :enrollments
  has_many :offer_dates, through: :enrollments
  has_many :courses, through: :offer_dates
  validates_presence_of :first_name, :last_name, :moz_number, :manager_id
  validates_uniqueness_of :moz_number

  CSV_COLUMNS_REQUIRED = [  # Moz Workday Nomenclature
    :first_name,            # Legal Name - First Name
    :last_name,             # Legal Name - Last Name
    :moz_number,            # Mozzer ID
    :manager_id,            # Mozzer's Manager
    :department             # Business Units
  ]

  def full_name
    "#{self.first_name} #{self.last_name}"
  end

  def self.import(file)
    row_id = 0
    response = {
      :new => 0,
      :updated => 0,
      :skipped => [],
      :bad_format => false
    }

    CSV.foreach(file.path,
      :headers => true,
      :converters => :all,
      :header_converters => lambda { |h| convert_column_name(h) }
    ) do |row|
        row = row.to_hash.extract!( *CSV_COLUMNS_REQUIRED )

        if ( row_id == 0 ) && !validate_header(row)
          response[:bad_format] = true
          break
        end

        if validate_row(row)
          s = Student.where( moz_number: row[:moz_number] ).first_or_initialize
          row[:manager_id] = get_manager_id(row)

          if s.update_attributes!(row)
            s.reload
            type = ( s.created_at == s.updated_at ) ? :new : :updated
            response[type] += 1
          else
            response[:skipped].push(row.values)
          end

        else
          # Validation failed
          response[:skipped].push(row.values)
        end

        row_id += 1
      end
    return response
  end

  private
  def self.convert_column_name(h)
    h.downcase.gsub(' - ', '').gsub(' ', '_').gsub('\'', '')
      .gsub('mozzers_manager', 'manager_id')
      .gsub('business_units', 'department')
      .gsub('employee_id', 'moz_number')
      .gsub('legal_name', '')
      .to_sym
  end

  def self.validate_header(row)
    ( CSV_COLUMNS_REQUIRED - row.keys ).empty?
  end

  def self.validate_row(row)
    ( row[:moz_number].is_a? Integer ) && ( row.all? { |k,v| !v.nil? } )
  end

  def self.get_manager_id(row)
    row[:manager_id][/\((\d+)\)/, 1]
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

    def index
        load_students
    end

    def new
        build_student
    end

    def create
        build_student
        success_message = "Student #{@student.full_name} successfully created."
        save_student(success_message, @student) ||
            fail_to_save('Student was not saved.', :new)
    end

    def show
        load_student
    end

    def edit
        load_student
        build_student
    end

    def update
        load_student
        build_student
        save_student('Student successfully updated.', @student) ||
            fail_to_save('Student was not updated.', :edit)
    end

    def import
        load_students
        r = Student.import(params[:file])
        err = "An error occurred. "
        if r[:bad_format]
            fail_to_import(err + "Expected columns or values were missing."\
                " No upload was processed.", students_url)
        elsif r[:skipped].count > 0
            fail_to_import(err + "Added #{r[:new]} new students, updated "\
                "#{r[:updated]}, and skipped #{r[:skipped].count}. "\
                "Skipped: #{r[:skipped]}", students_url)
        else
            msg = "Added #{r[:new]} new and updated #{r[:updated]} students."
            redirect_to students_url, notice: msg
        end
    end

  private
    def load_students
        @students ||= student_scope.to_a
    end

    def load_student
        @student ||= student_scope.find(params[:id])
    end

    def build_student
        @student ||= student_scope.build
        @student.attributes = student_params
    end

    def save_student(message, target)
        if @student.save
            redirect_to target, notice: message
        end
    end

    def fail_to_save(message, render_target)
        if message
            flash.now[:alert] = message
        end
        render render_target
    end

    def fail_to_import(message, target)
        redirect_to target, alert: message
    end

    def student_params
        student_params = params[:student]
        student_params ? student_params.permit(
            :first_name,
            :last_name,
            :department,
            :moz_number,
            :manager_id
        ) : {}
    end

    def student_scope
        Student.all
    end
end

app/views/students/_form.html.erb
<div class="row">
  <div class="col-md-4">

    <%= form_for @student do |f| %>
      <%= render 'shared/errors', object: @student %>
      <fieldset>
        <div class="form-group">
            <%= f.label :first_name %>
            <%= f.text_field :first_name, class: "form-control" %>
        </div>

        <div class="form-group">
            <%= f.label :last_name %>
            <%= f.text_field :last_name, class: "form-control" %>
        </div>

        <div class="form-group">
            <%= f.label :department %>
            <%= f.text_field :department, class: "form-control" %>
        </div>

        <div class="form-group">
            <%= f.label :moz_number, 'Mozzer ID' %>
            <%= f.text_field :moz_number, class: "form-control" %>
        </div>

        <div class="form-group">
            <%= f.label :manager_id, 'Manager ID' %>
            <%= f.text_field :manager_id, class: "form-control" %>
        </div>

        <%= f.submit nil, class: 'btn btn-primary' %>

      </fieldset>
    <% end %>

  </div>
</div>

app/views/students/edit.html.erb
<% content_for :title, "Edit Student" %>

<div class="page-header">
    <h1>Edit student</h1>
</div>

<%= render 'form' %>

app/views/students/index.html.erb
<% content_for :title, t('students.title') %>

<div class="page-header">
    <h1><%= "#{pluralize(@students.count, "student")}" %></h1>
</div>

<%= link_to new_student_path do %>
  <h5><i class="fa fa-plus-circle"></i> Add an New Student</h5>
<% end %>

<!-- begin import block -->
<a data-toggle="collapse" href="#collapseExample"
aria-expanded="false" aria-controls="collapseExample">
  <h5><i class="fa fa-upload"></i> Import Students from File</h5>
</a>

<div class="collapse" id="collapseExample" style="margin-top: 20px;">

    <script type="text/javascript">
      $( document ).ready(function() {
        $('#fileInput').change(function(){
           var filename = $(this).val().split('\\').pop();
           $('#selectedFile').text(filename);
           $('#importFile').removeClass( 'disabled' );
        });
      });
    </script>

    <div class="panel panel-info">
        <div class="panel-heading">
            <b>Select and import a file</b>
        </div>
    <div class="panel-body">

    <%= form_tag import_students_path, multipart: true do %>
      <span class="btn btn-large btn-default btn-file">
          <i class="fa fa-folder-open"></i> Select a File
          <%= file_field_tag :file, id: 'fileInput' %>
      </span>

      <%= submit_tag "Start Import",
        class: 'btn btn-primary disabled', id: 'importFile'
      %>
    <% end %>

    <p class="info-text" id="selectedFile">None</p>

      </div><!-- panel-body -->
    </div><!-- panel -->
</div><!-- collapse -->
<!-- end import block -->

<div class="widetable">
    <table id="students" class="ptrAppTable table table-striped table-bordered">
        <thead>
            <tr>
                <td>First Name</td>
                <td>Last Name</td>
                <td>Department</td>
                <td>Mozzer ID</td>
                <td>Manager ID</td>
            </tr>
        </thead>
        <tbody>

        <% @students.each do |s| %>
            <tr>
                <td><%= link_to "#{s.first_name}", student_url(s) %></td>
                <td><%= link_to "#{s.last_name}", student_url(s) %></td>
                <td><%= s.department %></td>
                <td><%= s.moz_number %></td>
                <td><%= s.manager_id %></td>
            </tr>
        <% end %>

        </tbody>
    </table>
</div>

app/views/students/new.html.erb
<% content_for :title, "Add Student" %>

<div class="page-header">
    <h1>Add a student</h1>
</div>

<%= render 'form' %>

app/views/students/show.html.erb
<% content_for :title, "Students" %>

<div class="page-header">
    <h1><%= "#{@student.first_name} #{@student.last_name}" %></h1>
</div>

<div class="panel panel-info">
  <div class="panel-heading">
    Student Mozzer ID <b><%= @student.moz_number %></b>
    <%= link_to edit_student_path(@student), title: "Edit Student" do %>
        <i data-toggle="tooltip" data-placement="right" title="Edit student information" class="glyphicon glyphicon-edit"></i>
    <% end %>
  </div>
  <div class="panel-body">
    <b>Department</b>: <%= @student.department %><br>
    <b>Manager ID</b>: <%= @student.manager_id %>
  </div>
</div>

<div class="panel panel-info">
  <div class="panel-heading">
    <b>Student Enrollment Information</b>
  </div>
  <div class="panel-body">

    <h2><%= "#{pluralize(@student.enrollments.count, "Enrollment")} for this Student" %></h2>
    <table id="enrollments" class="ptrAppTable table table-striped table-bordered">
      <thead>
        <tr>
          <td>Course Name</td>
          <td>Offer Date</td>
        </tr>
      </thead>
      <tbody>
        <% @student.offer_dates.each do |s| %>
        <tr>
          <td><%= link_to Course.find( s.course_id ).name, course_url(s.course_id) %></td>
          <td><%= s.date %></td>
        </tr>
        <% end %>
      </tbody>
    </table>

  </div><!-- panel-body -->
</div><!-- panel -->