config/routes.rb
Rails.application.routes.draw do

  # specific / named routes at top

  get 'sign_in', to: 'sessions#new', as: 'sign_in'
  post 'sign_in', to: 'sessions#create'
  get 'sign_out', to: 'sessions#destroy'
  get 'landing', to: 'pages#landing', as: 'landing'

  # resources in the middle

  resources :courses, only: [:index, :new, :create, :show, :edit, :update] do
    resources :offer_dates
  end

  resources :enrollments, only: [:index, :new, :create, :show]
  resources :students, only: [:index, :new, :create, :show, :edit, :update] do
    collection { post :import }
  end
  resources :users, only: [:index, :new, :create, :show, :edit, :update]

  # Translations example. Not in use. Probably won't work on Heroku.
  # resources :translations, only: [:index, :create]

  # nonspecific / catch-all routes at the bottom

  root to: 'home#index'
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true, email: true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    load_users
  end

  def new
    build_user
  end

  def create
    build_user
    save_user('User successfully created.', @user) ||
      fail_to_save('User was not created.', :new)
  end

  def show
    load_user
  end

  def edit
    load_user
  end

  def update
    load_user
    build_user
    save_user('User successfully updated.', @user) ||
      fail_to_save('User was not updated.', :edit)
  end

  private
    def load_users
      @users ||= user_scope.to_a
    end

    def load_user
      @user ||= user_scope.find(params[:id])
    end

    def build_user
      @user ||= user_scope.build
      @user.attributes = user_params
    end

    def save_user(message, target)
      if @user.save
        redirect_to target, notice: message
      end
    end

    def fail_to_save(message, render_target)
      if message
        flash.now[:alert] = message
      end
      render render_target
    end

    def user_params
      user_params = params[:user]
      user_params ? user_params.permit(
        :name,
        :email,
        :password,
        :password_confirmation
      ) : {}
    end

    def user_scope
      User.all
    end
end

app/views/users/_form.html.erb
<div class="row">
  <div class="col-md-4">

    <%= form_for @user do |f| %>
      <%= render 'shared/errors', object: @user %>
      <fieldset>
        <div class="form-group">
            <%= f.label :name %>
            <%= f.text_field :name, class: "form-control" %>
        </div>
        <div class="form-group">
            <%= f.label :email %>
            <%= f.email_field :email, class: "form-control" %>
        </div>
        <div class="form-group">
            <%= f.label :password %>
            <%= f.password_field :password, class: "form-control" %>
        </div>
        <div class="form-group">
            <%= f.label :password_confirmation %>
            <%= f.password_field :password_confirmation, class: "form-control" %>
        </div>
    
        <%= f.submit nil, class: 'btn btn-primary' %>
    
      </fieldset>
    <% end %>

  </div> 
</div

app/views/users/edit.html.erb
<% content_for :title, "Edit Offer Date" %>

<div class="page-header">
    <h1>Edit offer date</h1>
</div>

<%= render 'form' %>

app/views/users/index.html.erb
<% content_for :title, "Users" %>

<div class="page-header">
  <h1><%= "#{pluralize(@users.count, "user")}" %></h1>
</div>

<%= link_to new_user_path do %>
  <h5><i class="fa fa-plus-circle"></i> Add an New User</h5>
<% end %>

<div class="widetable">
  <table id="users" class="ptrAppTable table table-striped table-bordered">
    <thead>
      <tr>
        <td>Name</td>
        <td>Email</td>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= link_to "#{user.name}", user_url(user) %></td>
          <td><%= user.email %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/users/new.html.erb
<% content_for :title, "Add User" %>

<div class="page-header">
    <h1>Add a user</h1>
</div>

<%= render 'form' %>

app/views/users/show.html.erb
<% content_for :title, "Users" %>

<div class="page-header">
    <h1><%= @user.name %></h1>
</div>

<div class="panel panel-info">
  <div class="panel-heading">
    User ID <b><%= @user.id %></b>
    <%= link_to edit_user_path(@user), title: "Edit User" do %>
        <i data-toggle="tooltip" data-placement="right" title="Edit user information" class="glyphicon glyphicon-edit"></i>
    <% end %>
  </div>
  <div class="panel-body">
    <%= @user.email %>
  </div>
</div>