config/routes.rb
Rails.application.routes.draw do

  # specific / named routes at top

  get 'sign_in', to: 'sessions#new', as: 'sign_in'
  post 'sign_in', to: 'sessions#create'
  get 'sign_out', to: 'sessions#destroy'
  get 'landing', to: 'pages#landing', as: 'landing'

  # resources in the middle

  resources :courses, only: [:index, :new, :create, :show, :edit, :update] do
    resources :offer_dates
  end

  resources :enrollments, only: [:index, :new, :create, :show]
  resources :students, only: [:index, :new, :create, :show, :edit, :update] do
    collection { post :import }
  end
  resources :users, only: [:index, :new, :create, :show, :edit, :update]

  # Translations example. Not in use. Probably won't work on Heroku.
  # resources :translations, only: [:index, :create]

  # nonspecific / catch-all routes at the bottom

  root to: 'home#index'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
    end
end

app/views/home/index.html.erb
<div class="page-header">
    <h1>Pterodact Learning Management System</h1>
</div>

<div class="row">
  <div class="col-md-6">

    <div class="panel panel-primary">
      <div class="panel-heading">Dashboard</div>
      <div class="list-group">
        <%= link_to courses_url, { :class => "list-group-item do" } do %>
            Courses <span class="badge"><%= Course.count %></span>
        <% end %>

        <%= link_to students_url, { :class => "list-group-item do" } do %>
            Students <span class="badge"><%= Student.count %></span>
        <% end %>

        <%= link_to enrollments_url, { :class => "list-group-item do" } do %>
            Enrollments <span class="badge"><%= Enrollment.count %></span>
        <% end %>

        <%= link_to users_url, { :class => "list-group-item do" } do %>
            Users <span class="badge"><%= User.count %></span>
        <% end %>
      </div>
    </div>

  </div><!-- /col -->
</div><!-- /row -->

<hr>
<div>
  <a href="https://twitter.com/jmodjeska">
    <i class="fa fa-twitter" data-toggle="tooltip" data-placement="bottom" title="Visit @jmodjeska on Twitter"></i>
  </a> &nbsp;

  <a href="https://github.com/jmodjeska/pterodact">
    <i class="fa fa-github" data-toggle="tooltip" data-placement="bottom" title="Pterodact source on Github"></i>
  </a> &nbsp;

  <a href="http://creativecommons.org/licenses/by-sa/4.0/">
    <i class="fa fa-copyright" data-toggle="tooltip" data-placement="bottom" title="License CC-BY-SA 4.0"></i>
  </a>
</div>