config/routes.rb
Rails.application.routes.draw do

  # specific / named routes at top

  get 'sign_in', to: 'sessions#new', as: 'sign_in'
  post 'sign_in', to: 'sessions#create'
  get 'sign_out', to: 'sessions#destroy'
  get 'landing', to: 'pages#landing', as: 'landing'

  # resources in the middle

  resources :courses, only: [:index, :new, :create, :show, :edit, :update] do
    resources :offer_dates
  end

  resources :enrollments, only: [:index, :new, :create, :show]
  resources :students, only: [:index, :new, :create, :show, :edit, :update] do
    collection { post :import }
  end
  resources :users, only: [:index, :new, :create, :show, :edit, :update]

  # Translations example. Not in use. Probably won't work on Heroku.
  # resources :translations, only: [:index, :create]

  # nonspecific / catch-all routes at the bottom

  root to: 'home#index'
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to image_tag('ptr.png'), root_path, class: "navbar-brand" %>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Pterodact Home', root_path, class: "navbar-brand" %></li>

        <%= render select_navbar %>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
    <% if msg.is_a?(String) %>
        <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'warning' %>" role="alert-dismissible">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            <%= content_tag :div, msg %>
        </div>
    <% end %>
<% end %>

app/views/layouts/_nav_links.html.erb
<% case list %>
<% when 'view' %>
    <li><%= link_to('Courses', courses_path) %></li>
    <li><%= link_to('Students', students_path) %></li>
    <li><%= link_to('Enrollments', enrollments_path) %></li>
    <li><%= link_to('Users', users_path) %></li>
<% when 'add' %>
    <li><%= link_to('Course', new_course_path) %></li>
    <li><%= link_to('Student', new_student_path) %></li>
    <li><%= link_to('Enrollment', new_enrollment_path) %></li>
    <li><%= link_to('User', new_user_path) %></li>
<% end %>

app/views/layouts/_navbar_logged_in.html.erb
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">View <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <%= render 'layouts/nav_links', :list => 'view' %>
            </ul>
          </li>

          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Add New <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <%= render 'layouts/nav_links', :list => 'add' %>
            </ul>
          </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <p class="navbar-text">
          <span class="navbar-profile-image">
            <i class="glyphicon glyphicon-user"></i>
          </span>
          <%= get_user_email %>
        </p>
        <li class="dropdown">
          <% user_links.each do |link| %>
            <%= link_to link.name, link.target %>
          <% end %>
        </li>
      </ul>

app/views/layouts/_navbar_logged_out.html.erb
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <p class="navbar-text">
      </ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <%= favicon_link_tag 'favicon.ico' %>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? "Pterodact | #{yield :title}" : "Pterodact" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= yield :view_specific_css %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= render 'layouts/header' %>
    <%= render 'layouts/messages' %>

    <div class="container">

        <%= yield %>

    </div> <!-- /container -->

  </body>
</html>